spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
server:
  port: 8081
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full
