name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    #    env:
    #      working-directory: ./catalog-service
    #    defaults:
    #      run:
    #        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew :catalog-service:build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build Docker Image
        run: ./gradlew :catalog-service:bootBuildImage

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Publish Docker Image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/book-store-catalog-service:latest