name: Catalog Service

on:
  push:
    paths:
      - services/catalog-service/**
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
#    env:
#      working-directory: ./services/catalog-service
#    defaults:
#      run:
#        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Debug current directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in current directory:"
          ls -la

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew :services:catalog-service:build